<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net48</TargetFramework>
		<LangVersion>13</LangVersion>
		<Platforms>x64</Platforms>
		<ImplicitUsings>true</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\kusala.Model\kusala.Model.csproj" />
	  <ProjectReference Include="..\kusala.Revit\kusala.Revit.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="kusala.addin">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
